package com.example.nellamaster

sealed class Screen(val route: String) {
    object HomeScreen : Screen("home_screen")
    object AsienScreen : Screen("asien_screen")
    object JugenstilScreen : Screen("jugenstil_screen")
    object GotikScreen : Screen ("gotik_screen")
    object BauhausScreen : Screen("bauhaus_screen")
    object BarockScreen : Screen("barock_screen")
    object JapanScreen : Screen("japan_screen")
    object OrientScreen : Screen("indisch_screen")
    object RomScreen : Screen("rom_screen")
    object FullScreenRom : Screen("rom_full_screen")
    object ModerneScreen : Screen("moderne_scree")
    object FullScreenModerne : Screen("moderne_full_screen")
    object PostmoderneSceen : Screen("postmoderne_screen")
    object FullScreenPostmoderne : Screen("postmoderne_full_screen")
    object FullScreenJugendstil : Screen("jugendstil_full_screen")
    object FullScreenBarock : Screen("Barock_full_screen")
    object FullScreenAsien : Screen("Japanisch_full_screen")
    object FullScreenBauhaus : Screen("Bauhaus_full_screen")
    object FullScreenGotik : Screen("Gotik_full_screen")
    object FullScreenOrient : Screen("Orient_full_screen")
    object CategorySelection : Screen("Category_Selection")
    object ArchitectureInterior : Screen("Architecture_Interior_Screen")
    object KunstHandwerk : Screen("Kunst_Handwerk_Screen")
    object GrafikdesignPrint : Screen("Grafikdesign_Print_Screen")
    object WelcomeScreen1: Screen("Welchome_Screen_1")
    object WelcomeScreen2: Screen("Welchome_Screen_2")
    object WelcomeScreen3: Screen("Welchome_Screen_3")
    object WelcomeScreen4: Screen("Welchome_Screen_4")
    object ReadyToGoScreen: Screen("Ready_to_go")
    object HelpLandingScreen: Screen("Help_Landing_Screen")
    object QuizSelectorScreen: Screen("Quiz_selector_screen")
    object QuizJugendstilScreen: Screen("Quiz_jugendstil")
    object QuizBauhausScreen: Screen("Quiz_bauhaus")
    object QuizJapanScreen: Screen("Quiz_japan")
    object CameraMainScreen: Screen("Camera_main_screen")
    object TechnicalSupportScreen: Screen("Techsupport_screen")
    object AboutScreen: Screen("about_screen")
    object HelpAppNutzungScreen: Screen("helpapp_screen")
    object RightAnswerScreen: Screen("right_answer_screen")
    object CameraScreenNoAR: Screen("camera_screen_no_ar")
    object QuizCompletedScreen: Screen("quiz_completed_screen")
    object WrongAnswerScreenJugend: Screen("WrongAnswerScreenJu")
    object WrongAnswerScreenAsien: Screen("WrongAnswerScreenAs")
    object WrongAnswerScreenBauhaus: Screen("WrongAnswerScreenBau")
    object NavigationHelp1Screen: Screen("NaviagtionHelp1")
    object NavigationHelp2Screen: Screen("NaviagtionHelp2")
    object NavigationHelp3Screen: Screen("NaviagtionHelp3")
}
